language: java
jdk:
  - openjdk16
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:16-jre-slim-sid
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - ./mvnw clean install -Dmaven.test.skip=true
  - ./mvnw deploy jib:build -P deploy-docker