language: java
jdk:
  - openjdk16
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull adoptopenjdk/openjdk16:aarch64-debianslim-jdk-16.0.2_7-slim
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw heroku:deploy jib:build -P deploy-heroku,deploy-docker
after_success:
  - bash <(curl -s https://codecov.io/bash)